# Generated by Django 2.2.3 on 2019-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='User Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('passwd', models.CharField(max_length=20, verbose_name='password')),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
